### PR TITLE
Plugin consistency

### LINKED ISSUE #8: No Open Connections
I'm getting a no open connections error fairly frequently while developing our app. I see on line 25 of your MongoService module that you specifically call out that you're creating a new connection for each service. Are you providing a mechanism to control the number of connections, or whether or not it can reuse an open connection rather than create a new one?

### PR DESCRIPTION
**Pull request by ekryski**
This PR:
- makes this adapter consistent with the others in terms of documentation and file structure
- updates mongoskin dependency to the latest
- adds support for special query filters
    - $sort
    - $select
    - $skip
    - $limit
- Closes #8 by making sure that we autoreconnect by default when not passing a connection string

In order to be consistent with other adapters we now specify the collection like so:

```js
app.use('todos', mongoService('todos', options));
```

I've maintained the ability to pass it via options `{collection: 'todos'}` so as not to break backwords compatibility.

### CODE REVIEW

**Comment by ekryski** [comment]
@daffl I'll wait for you to review this as it has a breaking change and this is our most used adapter.

**Comment by daffl** [comment]
Can you squash the commits?

**Comment by daffl** [comment]
If we make it a breaking change we'd have to change all the examples. Can't we keep the original options object as well (if the first param isn't a string)?

**Comment by ekryski** [comment]
@daffl yup we can totally do that. I'll add it.

I've already updated the docs and examples in this repo, and in fact, all of the adapters repos except for `feathers-memory`. I can update any other docs as I'd like the string version to be the main documented way of doing things.

**Comment by daffl** [comment]
Cool. I don't think feathers-memory supports the `$` options yet so it might need some more work anyway. Also, I'm wondering if we should create a baseline test suite for all the adapters that make sure they all pass the exact same spec.

Also, commit message ;)

**Comment by ekryski** [comment]
Such a hard ass! :wink:

**Pull request merged**
