### PR TITLE
Fix mongoService construction, now accept the options parameter

### PR DESCRIPTION
**Pull request by PaGury**

### CODE REVIEW

**Comment by daffl** [comment]
Thanks, it looks like one of the tests is failing though. I think the documentation is actually wrong. At the moment you can either pass a string (which will be the collection name) or an options object (with  a `collection` property). I think this is a good fix but the test at https://github.com/feathersjs/feathers-mongodb/blob/master/test/test.js#L50 is failing now.

**Comment by PaGury** [comment]
Oups, didn't noticed. 
I think we should use this kind of configuration because passing an object containing the mongodb settings + the collection name is not effective if you have a lot of collections.

mongoService({ collection: 'col1', host: 'mongodb' });
mongoService({ collection: 'col2', host: 'mongodb' });
mongoService({ collection: 'col3', host: 'mongodb' });
mongoService({ collection: 'col4', host: 'mongodb' });

VS

var mongoConfig = { host: 'mongodb' };
mongoService('col1', mongoConfig);
mongoService('col2', mongoConfig);
mongoService('col3', mongoConfig);
mongoService('col4', mongoConfig);

So we can use the same configuration object for each mongoService we would create :+1: .

**Comment by PaGury** [comment]
I fixed the connectionString unit test

**Comment by daffl** [comment]
Sweet, thank you!

**Comment by daffl** [comment]
Fixed and released in version 1.0.1.

**Pull request merged**
